dist: trusty
sudo: required
os: linux
language: c
compiler:
  - gcc
  - clang

script:
  - ./autogen.sh
  - ./configure
  - make
  - make check
  - make distcheck
  - sudo make check
  - sudo make distcheck
